/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef mozilla_telemetry_histogram_h__
#define mozilla_telemetry_histogram_h__

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>
#include <cstdlib>

// A histogram created from static data for ranges.
struct StaticHistogram;

extern "C" {

// Add a single value to the given histogram.
void histogram_add(StaticHistogram *histogram, unsigned int sample);

// Create a new histogram from an external array of ranges.
StaticHistogram *histogram_factory_get(unsigned int min,
                                       unsigned int max,
                                       uintptr_t bucket_count,
                                       const unsigned int *ranges);

// Free a histogram's memory.
void histogram_free(StaticHistogram *histogram);

// Deallocate a null-terminated string.
void histogram_free_cstr(char *s);

// Serialize the histogram into a packed representation.
//
// The returned data is null-terminated. It should be passed back to `histogram_free_cstr` to
// deallocate after usage.
char *histogram_serialize(StaticHistogram *histogram);

// Serialize the histogram into a persistable JSON string.
//
// The returned data is null-terminated. It should be passed back to `histogram_free_cstr` to
// deallocate after usage.
char *histogram_serialize_persist(StaticHistogram *histogram);

} // extern "C"

#endif // mozilla_telemetry_histogram_h__
